project:
  output-dir: docs 
  type: website

website:
  favicon: images/robbiencsu64.jpg
  navbar:
    title: "ROBBIE MICHAEL FERRAND"
    left:
      - text: "Projects"
        menu:
        - href: projects/
          text: "Projects Overview"
        - href: projects/turtles/
          text: "Metal Concentrations in Turtles"
        - href: projects/matriculation/
          text: "Crime Rate and Matriculation Rate of Schools"
        - href: projects/mobiledata/
          text: "Mobile Data Exploratory Analysis"
      - text: "Work Experience"
        href: work/
      - text: "Education"
        href: education/
      - text: "Resume"
        href: assets/RobbieFerrand_Resume.pdf
      - text: "Hobbies and Interests"
        href: hobbies/
      - text: "Contact Me"
        href: contact/

resources:
  - images

format:
  html:
    theme: united
    css: styles.css
    
    
    

